apiVersion: batch/v1
kind: Job
metadata:
  name: cntdwntmr-job
spec:
  template:
    spec:
      containers:
      - name: cntdwntmr-job
        image: yash5090/cntdwntmr:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
